[package]
name = "stratoneers"
version = "0.1.0"
authors = ["Andre Cox"]
edition = "2018"

[dependencies]
chrono = "0.4.26"
indicatif = "0.17.6"
rayon = "1.7.0"
rodio = "0.17.1"

[dependencies.paris]
version = "1.5.15"
features = ["timestamps", "macros"]

